version: '3.8'
services:
#  front-end:
#     build: ./my-app
#     ports:
#       - 3000:3000
#     volumes:
#       - ./my-app:/app
#  back-end:
#     build: ./Back-end 
#     volumes:
#     - /app/node_modules 
#     - ./Back-end:/app 
#     ports:
#      - 9090:9090    
#     depends_on:
#      - db
 db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: thala_fdarak
    ports:
      - "5432:5432"
 pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"