const userModel = require('./userModel')
const promotionModel = require('./promotionModel')
const productModel = require('./productModel')
const view_commentaire = require('./view_commentaire')
const categorie = require('./categorieModel')
const commande = require('./commandeModel')
const product_commande = require('./produitCommandeModel')
const favorie = require('./favorieModel')

const product_favorie = require('./productFavorieModel')